version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/arbicrypt
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
